# Generated by Django 5.2.9 on 2026-01-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True, verbose_name='Чернетка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('resumesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resumes.resumesection')),
                ('institution', models.CharField(max_length=100, verbose_name='Установа')),
                ('speciality', models.CharField(max_length=100, verbose_name='Спеціальність')),
                ('degree', models.CharField(max_length=255, verbose_name='Степень')),
                ('start_year', models.PositiveIntegerField(verbose_name='Дата початку навчання')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дата закінчення навчання')),
            ],
            bases=('resumes.resumesection',),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('resumesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resumes.resumesection')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('description', models.TextField(max_length=1000, verbose_name="Обов'язки")),
                ('why_fired', models.CharField(max_length=100, verbose_name='Причина звілнення')),
                ('start_date', models.DateField(verbose_name='Дата початку роботи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата звільнення')),
            ],
            bases=('resumes.resumesection',),
        ),
        migrations.AddField(
            model_name='resumesection',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resumes.resume'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва скіла')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resumesection', verbose_name='Секція')),
            ],
        ),
    ]
