# Generated by Django 5.2.9 on 2026-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядок'),
        ),
    ]
