# Generated by Django 5.2.9 on 2026-01-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resumesection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
