# Generated by Django 5.2.9 on 2026-01-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_resumesection_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='SkillItem',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resumesection_ptr',
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='Навчальний заклад')),
                ('speciality', models.CharField(max_length=100, verbose_name='Спеціальність')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('degree', models.CharField(max_length=255, verbose_name='Ступінь')),
                ('start_year', models.DateField(verbose_name='Дата початку навчання')),
                ('end_year', models.DateField(blank=True, null=True, verbose_name='Дата закінчення навчання')),
                ('description', models.TextField(max_length=1000, verbose_name='Опис')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resumesection', verbose_name='Секція')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('why_fired', models.CharField(max_length=100, verbose_name='Причина звілнення')),
                ('start_date', models.DateField(verbose_name='Дата початку роботи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата звільнення')),
                ('description', models.TextField(max_length=1000, verbose_name='Опис')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resumesection', verbose_name='Секція')),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
