# Generated by Django 5.2.6 on 2026-01-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_rename_skill_skillitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateInformationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=15, verbose_name='Прізвище')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='resume_avatars/', verbose_name='Аватар')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна адреса')),
                ('city', models.CharField(max_length=100, verbose_name='Місто проживання')),
                ('gender', models.CharField(choices=[('-', 'Не обрано'), ('female', 'Жіноча'), ('male', 'Чоловіча')], max_length=9, verbose_name='Стать')),
                ('marial', models.CharField(choices=[('-', 'Не обрано'), ('married', 'Одружений'), ('not_married', 'Не одружений')], max_length=15, verbose_name='Сімейний стан')),
                ('github_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Посилання на Гітхаб')),
                ('other_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Посилання')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resumesection', verbose_name='Секція')),
            ],
            options={
                'verbose_name': 'Персональна інформація',
                'verbose_name_plural': 'Персональна інформація',
            },
        ),
    ]
