# Generated by Django 5.2.6 on 2026-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_privateinformationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinformationitem',
            name='marial',
            field=models.CharField(choices=[('married', 'Одружений'), ('not_married', 'Не одружений')], max_length=15, verbose_name='Сімейний стан'),
        ),
    ]
