# Generated by Django 5.2.9 on 2026-02-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_alter_privateinformationitem_marial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinformationitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resumes.resumesection', verbose_name='Секція'),
        ),
    ]
