# Generated by Django 5.2.9 on 2026-02-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_alter_privateinformationitem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateinformationitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resumesection', verbose_name='Секція'),
        ),
    ]
